# Generated by Django 5.0.2 on 2025-06-02 13:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buildings', '0002_alter_building_options'),
        ('contracts', '0005_alter_contract_monthly_rent'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='الاسم')),
                ('email', models.EmailField(max_length=255, verbose_name='البريد الالكتروني')),
                ('message', models.TextField(verbose_name='الرسالة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='التاريخ')),
            ],
            options={
                'verbose_name': 'الاتصال',
                'verbose_name_plural': 'الاتصالات',
            },
        ),
        migrations.CreateModel(
            name='CommunicationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('call', 'اتصال'), ('email', 'بريد إلكتروني'), ('whatsapp', 'واتساب'), ('sms', 'رسالة نصية')], max_length=50, verbose_name='طريقة التواصل')),
                ('subject', models.CharField(max_length=255, verbose_name='الموضوع')),
                ('content', models.TextField(verbose_name='المحتوى')),
                ('date_sent', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإرسال')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant', verbose_name='المستأجر')),
            ],
        ),
        migrations.CreateModel(
            name='EvictionNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateField(verbose_name='تاريخ الإصدار')),
                ('reson', models.TextField(verbose_name='سبب الطرد')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts.contract', verbose_name='العقد')),
                ('issued_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='أصدر بواسطة')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant', verbose_name='المستأجر')),
            ],
        ),
        migrations.CreateModel(
            name='MoveOutNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice_date', models.DateField(verbose_name='تاريخ الإشعار')),
                ('move_out_date', models.DateField(verbose_name='تاريخ الإخلاء المتوقع')),
                ('reason', models.TextField(verbose_name='سبب الإخلاء')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts.contract', verbose_name='العقد')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant', verbose_name='المستأجر')),
            ],
            options={
                'verbose_name': 'إشعار الإخلاء',
                'verbose_name_plural': 'إشعارات الإخلاء',
            },
        ),
        migrations.CreateModel(
            name='ServiceRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='التقييم')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='التعليق')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='التاريخ')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant', verbose_name='المستأجر')),
            ],
        ),
        migrations.CreateModel(
            name='UnitTourVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_name', models.CharField(max_length=255, verbose_name='اسم الزائر')),
                ('phone', models.CharField(max_length=20, verbose_name='رقم الهاتف')),
                ('visit_date', models.DateField(verbose_name='تاريخ الزيارة')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buildings.unit', verbose_name='الوحدة')),
            ],
            options={
                'verbose_name': 'زيارة الوحدة',
                'verbose_name_plural': 'زيارات الوحدات',
            },
        ),
    ]
