# Generated by Django 5.0.2 on 2025-06-03 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_helpcontact_unitreporttype_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_office_fee', models.DecimalField(decimal_places=3, default=5.0, max_digits=10, verbose_name='رسوم المكتب (ريال عماني)')),
                ('admin_fee', models.DecimalField(decimal_places=3, default=1.0, max_digits=10, verbose_name='رسوم الإدارة (ريال عماني)')),
                ('commission_rate', models.DecimalField(decimal_places=2, default=0.03, max_digits=5, verbose_name='نسبة العمولة (%)')),
            ],
            options={
                'verbose_name': 'إعدادات النظام',
                'verbose_name_plural': 'إعدادات النظام',
            },
        ),
        migrations.RemoveField(
            model_name='communicationlog',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='tenant',
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.RemoveField(
            model_name='evictionnotice',
            name='contract',
        ),
        migrations.RemoveField(
            model_name='evictionnotice',
            name='issued_by',
        ),
        migrations.RemoveField(
            model_name='evictionnotice',
            name='tenant',
        ),
        migrations.DeleteModel(
            name='HelpContact',
        ),
        migrations.RemoveField(
            model_name='moveoutnotice',
            name='contract',
        ),
        migrations.RemoveField(
            model_name='moveoutnotice',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='servicerating',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='unitreport',
            name='report_type',
        ),
        migrations.RemoveField(
            model_name='unitreport',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='unitreport',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='unitreportalbum',
            name='report',
        ),
        migrations.RemoveField(
            model_name='unittourvisit',
            name='unit',
        ),
        migrations.DeleteModel(
            name='CommunicationLog',
        ),
        migrations.DeleteModel(
            name='Complaint',
        ),
        migrations.DeleteModel(
            name='EvictionNotice',
        ),
        migrations.DeleteModel(
            name='MoveOutNotice',
        ),
        migrations.DeleteModel(
            name='ServiceRating',
        ),
        migrations.DeleteModel(
            name='UnitReportType',
        ),
        migrations.DeleteModel(
            name='UnitReport',
        ),
        migrations.DeleteModel(
            name='UnitReportAlbum',
        ),
        migrations.DeleteModel(
            name='UnitTourVisit',
        ),
    ]
