# Generated by Django 5.0.2 on 2025-05-31 12:50

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buildings', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=datetime.date.today, verbose_name='تاريخ البداية')),
                ('end_date', models.DateField(verbose_name='تاريخ النهاية')),
                ('monthly_rent', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='الإيجار الشهري')),
                ('admin_fees', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='رسوم إدارية')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant', verbose_name='المستأجر')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buildings.unit', verbose_name='الوحدة')),
            ],
            options={
                'verbose_name': 'عقد',
                'verbose_name_plural': 'العقود',
            },
        ),
    ]
