# Generated by Django 5.0.3 on 2025-05-31 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='monthly_rent',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='الإيجار الشهري (ريال عماني)'),
        ),
    ]
