# Generated by Django 5.0.2 on 2025-06-01 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_alter_contract_monthly_rent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='admin_fees',
        ),
        migrations.AlterField(
            model_name='contract',
            name='monthly_rent',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='الإيجار الشهري (ريال عماني)'),
        ),
    ]
