# Generated by Django 5.0.2 on 2025-06-01 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0004_remove_contract_admin_fees_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='monthly_rent',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='الإيجار الشهري (ريال عماني)'),
        ),
    ]
