# Generated by Django 5.0.2 on 2025-06-02 14:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='المحافظة')),
            ],
            options={
                'verbose_name': 'المحافظة',
                'verbose_name_plural': 'المحافظات',
            },
        ),
        migrations.CreateModel(
            name='UnitType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نوع الوحدة')),
            ],
            options={
                'verbose_name': 'نوع الوحدة',
                'verbose_name_plural': 'أنواع الوحدات',
            },
        ),
        migrations.CreateModel(
            name='Estate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='المجمع')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.county', verbose_name='المحافظة')),
            ],
            options={
                'verbose_name': 'المجمع',
                'verbose_name_plural': 'المجمعات',
            },
        ),
        migrations.CreateModel(
            name='EstateBuilding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم المبنى')),
                ('address', models.CharField(max_length=255, verbose_name='العنوان')),
                ('estate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.estate', verbose_name='المجمع')),
            ],
            options={
                'verbose_name': 'مبنى المجمع',
                'verbose_name_plural': 'مباني المجمع',
            },
        ),
        migrations.CreateModel(
            name='RentalUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_number', models.CharField(max_length=255, verbose_name='رقم الوحدة')),
                ('floor', models.PositiveIntegerField(verbose_name='الطابق')),
                ('size', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المساحة')),
                ('is_available', models.BooleanField(default=True, verbose_name='متاح')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.estatebuilding', verbose_name='المبنى')),
                ('unit_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.unittype', verbose_name='نوع الوحدة')),
            ],
            options={
                'verbose_name': 'وحدة للإيجار',
                'verbose_name_plural': 'وحدات للإيجار',
                'unique_together': {('building', 'unit_number')},
            },
        ),
        migrations.CreateModel(
            name='MaintenanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255, verbose_name='الموضوع')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('scheduled_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الجدولة')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.rentalunit', verbose_name='الوحدة')),
            ],
            options={
                'verbose_name': 'طلب الصيانة',
                'verbose_name_plural': 'طلبات الصيانة',
            },
        ),
        migrations.CreateModel(
            name='UnitImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='unit_images/', verbose_name='الصورة')),
                ('caption', models.CharField(blank=True, max_length=255, null=True, verbose_name='التعليق')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.rentalunit', verbose_name='الوحدة')),
            ],
            options={
                'verbose_name': 'صورة الوحدة',
                'verbose_name_plural': 'صور الوحدات',
            },
        ),
    ]
