# Generated by Django 5.0.2 on 2025-06-02 14:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buildings', '0002_alter_building_options'),
        ('contracts', '0005_alter_contract_monthly_rent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='طريقة الدفع')),
            ],
            options={
                'verbose_name': 'طريقة الدفع',
                'verbose_name_plural': 'طرق الدفع',
            },
        ),
        migrations.CreateModel(
            name='ElectricityBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=20, verbose_name='الشهر')),
                ('consumption', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='الاستهلاك')),
                ('rate', models.DecimalField(decimal_places=2, default=0.2, max_digits=10, verbose_name='السعر')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buildings.unit', verbose_name='الوحدة')),
            ],
            options={
                'verbose_name': 'فاتورة الكهرباء',
                'verbose_name_plural': 'فواتير الكهرباء',
            },
        ),
        migrations.CreateModel(
            name='RentalDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_rent', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='الإيجار الشهري')),
                ('service_charge', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='رسوم الخدمة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buildings.unit', verbose_name='الوحدة')),
            ],
            options={
                'verbose_name': 'تفاصيل الإيجار',
                'verbose_name_plural': 'تفاصيل الإيجار',
            },
        ),
        migrations.CreateModel(
            name='RentPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ')),
                ('month', models.CharField(max_length=20, verbose_name='الشهر')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ المدفوع')),
                ('payment_date', models.DateField(verbose_name='تاريخ الدفع')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts.contract', verbose_name='العقد')),
                ('received_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='استلم بواسطة')),
            ],
            options={
                'verbose_name': 'دفع الإيجار',
                'verbose_name_plural': 'دفعات الإيجار',
            },
        ),
        migrations.CreateModel(
            name='UtilityPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_type', models.CharField(choices=[('water', 'فاتورة المياه'), ('electricity', 'فاتورة الكهرباء')], max_length=20, verbose_name='نوع الفاتورة')),
                ('month', models.CharField(max_length=20, verbose_name='الشهر')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ المدفوع')),
                ('payment_date', models.DateField(verbose_name='تاريخ الدفع')),
                ('received_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='استلم بواسطة')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buildings.unit', verbose_name='الوحدة')),
            ],
            options={
                'verbose_name': 'دفع الفاتورة',
                'verbose_name_plural': 'دفعات الفواتير',
            },
        ),
        migrations.CreateModel(
            name='WaterBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=20, verbose_name='الشهر')),
                ('consumption', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='الاستهلاك')),
                ('rate', models.DecimalField(decimal_places=2, default=0.8, max_digits=10, verbose_name='السعر')),
                ('issued_at', models.DateField(verbose_name='تاريخ الإصدار')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buildings.unit', verbose_name='الوحدة')),
            ],
            options={
                'verbose_name': 'فاتورة المياه',
                'verbose_name_plural': 'فواتير المياه',
            },
        ),
    ]
