# Generated by Django 5.0.2 on 2025-06-02 14:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='electricitybill',
            name='issued_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='تاريخ الإصدار'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rentpayment',
            name='method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='utilities.paymentmethod', verbose_name='طريقة الدفع'),
        ),
        migrations.AlterField(
            model_name='electricitybill',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=0.12, max_digits=10, verbose_name='السعر'),
        ),
    ]
