# Generated by Django 5.0.2 on 2025-06-02 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0002_electricitybill_issued_at_rentpayment_method_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentpayment',
            name='amount',
        ),
    ]
