# Generated by Django 5.0.2 on 2025-06-02 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='building',
            options={'ordering': ['name'], 'verbose_name': 'مبني', 'verbose_name_plural': 'المباني'},
        ),
    ]
