# Generated by Django 5.0.2 on 2025-06-02 14:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buildings', '0002_alter_building_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HiredPersonnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='الاسم الكامل')),
                ('specialty', models.CharField(max_length=100, verbose_name='التخصص')),
                ('available', models.BooleanField(default=True, verbose_name='متاح للعمل؟')),
            ],
            options={
                'verbose_name': 'فني/عامل',
                'verbose_name_plural': 'الفنيين/العمال',
            },
        ),
        migrations.CreateModel(
            name='PersonnelContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, verbose_name='رقم الهاتف')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='البريد الإلكتروني')),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='workorders.hiredpersonnel', verbose_name='الفني')),
            ],
            options={
                'verbose_name': 'بيانات تواصل الفني',
                'verbose_name_plural': 'بيانات التواصل',
            },
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان الأمر')),
                ('description', models.TextField(verbose_name='وصف المشكلة')),
                ('scheduled_date', models.DateField(verbose_name='تاريخ التنفيذ')),
                ('is_completed', models.BooleanField(default=False, verbose_name='تم التنفيذ؟')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='أضيف بواسطة')),
                ('personnel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workorders.hiredpersonnel', verbose_name='الفني المسؤول')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buildings.unit', verbose_name='الوحدة')),
            ],
            options={
                'verbose_name': 'أمر عمل',
                'verbose_name_plural': 'أوامر العمل',
            },
        ),
        migrations.CreateModel(
            name='WorkOrderPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='المبلغ')),
                ('paid_on', models.DateField(auto_now_add=True, verbose_name='تاريخ الدفع')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='workorders.workorder', verbose_name='أمر العمل')),
            ],
            options={
                'verbose_name': 'مدفوعات أمر العمل',
                'verbose_name_plural': 'مدفوعات أوامر العمل',
            },
        ),
    ]
